name: JUG Karlsruhe
description: JUG Karlsruhe

plugins:
 - jekyll-paginate
 - jekyll_version_plugin
paginate_path: "blog/page:num/"
paginate: 5

permalink: content/:title/

markdown: redcarpet
timezone: Europe/Berlin

navigation:
 - title: Home
   url: /index.html
 - title: Veranstaltungen
   url: /events
 - title: Hall of Fame
   url: /speakers
 - title: Kontakt
   url: /contact
 - title: Impressum
   url: /imprint
 - title: Datenschutz
   url: /privacy
