name: JUG Karlsruhe
description: JUG Karlsruhe

gems:
 - jekyll-paginate
 - jekyll_version_plugin
paginate_path: "blog/page:num/"
paginate: 5

permalink: content/:title/

markdown: redcarpet
timezone: Europe/Berlin

url: jug-ka.de

navigation:
 - title: Home
   url: /index.html
 - title: Veranstaltungen
   url: /events
 - title: Hall of Fame
   url: /speakers
 - title: Kontakt
   url: /contact
