name: JUG Karlsruhe
description: JUg Karlsruhe

gems: [jekyll-paginate]
paginate_path: "blog/page:num/"
paginate: 5

permalink: content/:title/

markdown: redcarpet
timezone: Europe/Berlin

url: jug-ka.surge.sh

navigation:
 - title: Home
   url: /index.html
 - title: Veranstaltungen
   url: /events
 - title: Hall of Fame
   url: /speakers
 - title: Kontakt
   url: /contact
